export const ATTR_ROOT = "torph-root";
export const ATTR_ITEM = "torph-item";
export const ATTR_ID = "torph-id";
export const ATTR_KIND = "torph-kind";
export const ATTR_SLOT = "torph-slot";
export const ATTR_NODE = "torph-node";
export const ATTR_FORMATTED = "torph-format"; // The format a reused item is wearing.
export const ATTR_GROUP = "torph-group"; // A run's real wrapper — never a segment.
export const ATTR_EXITING = "torph-exiting";
export const ATTR_SR = "torph-sr"; // Not a segment — every walk of root.children skips it.
export const ATTR_DEBUG = "torph-debug";
export const ATTR_WRAP = "torph-wrap";
export const EMPTY_ID = "empty";
